### ISSUE TITLE
Указать, какие параметры нужно передавать в запрос авторизации на майнкрафт сервер

### ISSUE THREAD

**Issue by semenishchev** [elyby/docs#12]

**Comment by erickskrauch** [comment]
Можно, конечно, но я не совсем понимаю, какой в этом смысл: что со стороны клиента, что со стороны сервера, реализация готовая, а протокол стандартизирован и не имеет отличий от оригинального протокола Mojang. В документации ведь об этом также говорится.

Можете пояснить, зачем детализировать эту часть документации?

**Comment by erickskrauch** [comment]
Поскольку прошло уже почти 3 года, а ответ так и не был получен, закрываю.
