### ISSUE TITLE
Pages not fully translated.

### ISSUE THREAD

**Issue by CubeNotFound** [elyby/docs#18]
English pages aren't translated fully (if even).

**Comment by erickskrauch** [comment]
Can you please provide examples?

**Comment by Octol1ttle** [comment]
> Can you please provide examples?

![image](https://github.com/elyby/docs/assets/61277953/a8b7708d-1e91-4673-b359-ea245d265b58)
![image](https://github.com/elyby/docs/assets/61277953/d3e331c0-8442-41a9-9742-94fa7cf77d96)

**Comment by erickskrauch** [comment]
Yeah, those 2 articles aren't translated at all. I need to spend some time translating them from Russian to English. Volunteers are welcome :)
![image](https://github.com/elyby/docs/assets/4787256/f6199e05-3b50-4032-b572-b192be43f3b1)

**Comment by erickskrauch** [comment]
The remaining pages have been translated with help from @Octol1ttle :heart:
