### ISSUE TITLE
Исправление документации API

### ISSUE THREAD

**Issue by EgorovUser** [elyby/docs#4]
https://github.com/elyby/docs/blob/master/source/ru/oauth.rst#получение-информации-о-пользователе
В примере поменять ссылку на корректную (https://account.ely.by/api/account/v1/info)

https://account.ely.by/api/account/v1/info
На сайте документации, входные параметры отображаются с большой буквы, хотя принимаются только первой маленькой

**Comment by erickskrauch** [comment]
Привет. Сможешь создать PR с исправлением ссылки?

Касательно автоматических заглавных букв в параметрах, да, такая проблема есть. В исходных RST файлах всё корректно, но результирующие файлы отформатированы так, чтобы значения всегда начинались с заглавной буквы. Я позже посмотрю, что с этим можно сделать.

**Comment by EgorovUser** [comment]
Не, я с Pull requests вообще не работал и не знаю, как правильно сделать
